---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: loading-packages
#| message: false 

library(tidyverse)
library(maps)

```

```{r}
#| label: loading-datasets
#| message: false

#loading datasets childcare_costs and counties from tidytuesday

#loading dataset childcare_costs
childcare_costs <- read_csv("data/childcare_costs.csv")

#loading dataset counties
counties <- read_csv("data/counties.csv")

#loading dataset expenditures
expenditures <- read_csv("data/kids.csv")

#loading dataset scores
scores <- read_csv("data/scores.csv")

#loading us map 
us_states <- map_data("state")

expenditures
```

Code for us_states from Kieran Healy: `https://socviz.co/maps.html#map-u.s.-state-level-data`

```{r}
#| label: us-map

expenditures_PK12ed <- expenditures |> 
  mutate(region = str_to_lower(state)) |>
  filter(variable == "PK12ed")

us_states_expenditures <- us_states |>
  select(-subregion) |>
  inner_join(expenditures_PK12ed, join_by(region == region), relationship = "many-to-many")
```

```{r}
ggplot(us_states_expenditures, aes(x = long, y = lat, group = group, fill = inf_adj_perchild)) +
  geom_polygon() +
  guides(fill = FALSE) + 
  theme_void() + 
  scale_fill_gradient(low = "white", high = "navyblue")
```

```{r}

scores_new <- scores |> 
  mutate(region = str_to_lower(Jurisdiction), MN = as.numeric(MN))

us_states_scores <- us_states |>
  select(-subregion) |>
  inner_join(scores_new, join_by(region == region), relationship = "many-to-many")

ggplot(us_states_scores, aes(x = long, y = lat, group = group, fill = MN)) +
  geom_polygon() +
  guides(fill = FALSE) + 
  theme_void() + 
  scale_fill_gradient(low = "white", high = "navyblue")
```
